region               = "us-east-1"
profile              = "default"
table_name           = "website_visitors"
s3_bucket_name       = "alismed-static-website"
lambda_function_name = "countVisitors"
lambda_runtime       = "python3.12"
index_document       = "index.html"
error_document       = "error.html"