name: 01 - Start

on:
  pull_request:
    types: opened
    branches: [ feature/* ]

jobs:
  validate:
    uses: ./.github/workflows/02-validate.yml

  deploy:
    needs: validate
    uses: ./.github/workflows/03-terraform.yml
    with:
      destroy_infra: ${{ needs.validate.outputs.destroy_infra }}
      region: ${{ needs.validate.outputs.region }}
    secrets: inherit

  notify:
    needs: [validate, deploy]
    uses: ./.github/workflows/04-notify.yml
    permissions:
      pull-requests: write
